CREATE TABLE  ADMINISTRATION
   (	A_ID VARCHAR2(8), 
	A_NAME VARCHAR2(25), 
	ADDRESS VARCHAR2(20), 
	DESIGNATION VARCHAR2(40), 
	QUALIFICATION VARCHAR2(20), 
	PH_NO NUMBER(10,0), 
	BLOOD_GROUP VARCHAR2(3), 
	YEAR_OF_EXP NUMBER(2,0), 
	PASSWORD VARCHAR2(12), 
	 PRIMARY KEY (A_ID) 
   );

CREATE TABLE  BILLING 
   (	BILL_NUMBER NUMBER, 
	P_ID VARCHAR2(8) NOT NULL , 
	P_NAME VARCHAR2(20), 
	P_TYPE VARCHAR2(20), 
	DOCTOR_CHARGES NUMBER, 
	LAB_CHARGES NUMBER, 
	WARD_CHARGES NUMBER, 
	NO_OF_DAYS NUMBER, 
	OTHER_CHARGES NUMBER, 
	TOTAL NUMBER, 
	CURRENT_DATE DATE NOT NULL , 
	 CONSTRAINT "BILLING_PK" PRIMARY KEY ("BILL_NUMBER") ENABLE, 
	 CONSTRAINT "BILLING_UK1" UNIQUE ("P_ID") DISABLE, 
	 CONSTRAINT "BILLING_FK" FOREIGN KEY ("P_ID")
	  REFERENCES  "PATIENT" ("P_ID") ENABLE
   )


CREATE TABLE  "DOCTOR" 
   (	"D_ID" VARCHAR2(8), 
	"D_NAME" VARCHAR2(25), 
	"DEPARTMENT" VARCHAR2(20), 
	"AGE" NUMBER(2,0), 
	"GENDER" CHAR(1), 
	"ADDRESS" VARCHAR2(25), 
	"SALARY" NUMBER, 
	"PH_NO" NUMBER(10,0), 
	"BLOOD_GROUP" VARCHAR2(3), 
	"PASSWORD" VARCHAR2(12), 
	 PRIMARY KEY ("D_ID") ENABLE
   )






CREATE TABLE  "INPATIENT" 
   (	"P_ID" VARCHAR2(8) NOT NULL ENABLE, 
	"P_NAME" VARCHAR2(20), 
	"WARD_NO" NUMBER, 
	"DATE_OF_ADMISSION" DATE NOT NULL ENABLE, 
	"DATE_OF_DISCHARGE" DATE, 
	"LAB_NO" NUMBER, 
	"N_ID" VARCHAR2(8), 
	"D_ID" VARCHAR2(8), 
	"PH_NO" NUMBER(10,0), 
	"DISEASE" VARCHAR2(30), 
	 CONSTRAINT "INPATIENT_CON" UNIQUE ("P_ID") ENABLE, 
	 CONSTRAINT "INPATIENT_FK" FOREIGN KEY ("P_ID")
	  REFERENCES  "PATIENT" ("P_ID") ENABLE, 
	 CONSTRAINT "INPATIENT_FK2" FOREIGN KEY ("WARD_NO")
	  REFERENCES  "WARDS" ("WARD_NO") ENABLE, 
	 CONSTRAINT "INPATIENT_FK3" FOREIGN KEY ("LAB_NO")
	  REFERENCES  "LAB" ("LAB_NO") ENABLE, 
	 CONSTRAINT "INPATIENT_FK4" FOREIGN KEY ("N_ID")
	  REFERENCES  "NURSE" ("N_ID") ENABLE, 
	 CONSTRAINT "INPATIENT_FK5" FOREIGN KEY ("D_ID")
	  REFERENCES  "DOCTOR" ("D_ID") ENABLE
   )





CREATE TABLE  "LAB" 
   (	"LAB_NO" NUMBER, 
	"LAB_TYPE" VARCHAR2(30), 
	 CONSTRAINT "LAB_PK" PRIMARY KEY ("LAB_NO") ENABLE
   )



CREATE TABLE  "NURSE" 
   (	"N_ID" VARCHAR2(8), 
	"N_NAME" VARCHAR2(25), 
	"ADDRESS" VARCHAR2(25), 
	"SALARY" NUMBER, 
	"BLOOD_GROUP" VARCHAR2(3), 
	"PASSWORD" VARCHAR2(12), 
	"PH_NO" NUMBER(10,0), 
	 PRIMARY KEY ("N_ID") ENABLE
   )


CREATE TABLE  "PATIENT" 
   (	"P_ID" VARCHAR2(8), 
	"P_NAME" VARCHAR2(20), 
	"AGE" NUMBER, 
	"GENDER" VARCHAR2(6), 
	"TIME" VARCHAR2(30) NOT NULL ENABLE, 
	"BLOOD_GROUP" VARCHAR2(3), 
	"ADDRESS" VARCHAR2(25), 
	"APPOINTMENT_DATE" DATE, 
	"DOCTOR_ID" VARCHAR2(8) NOT NULL ENABLE, 
	"R_ID" VARCHAR2(8) NOT NULL ENABLE, 
	"PH_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"D_NAME" VARCHAR2(20), 
	"LAB_NO" NUMBER(10,0), 
	"DISEASE" VARCHAR2(25), 
	 CONSTRAINT "PATIENT_PK" PRIMARY KEY ("P_ID") ENABLE, 
	 CONSTRAINT "PATIENT_FK" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES  "DOCTOR" ("D_ID") ENABLE, 
	 CONSTRAINT "PATIENT_FK2" FOREIGN KEY ("R_ID")
	  REFERENCES  "RECEPTIONIST" ("R_ID") ENABLE, 
	 CONSTRAINT "PATIENT_CON" FOREIGN KEY ("LAB_NO")
	  REFERENCES  "LAB" ("LAB_NO") ENABLE
   )



CREATE TABLE  "RADIOLOGY" 
   (	"P_ID" VARCHAR2(8) NOT NULL ENABLE, 
	"P_NAME" VARCHAR2(25), 
	"D_ID" VARCHAR2(8) NOT NULL ENABLE, 
	"SCAN_NAME" VARCHAR2(40), 
	"BILL_AMOUNT" NUMBER, 
	"D_NAME" VARCHAR2(25), 
	 CONSTRAINT "RADIOLOGY_PK" PRIMARY KEY ("SCAN_NAME") DISABLE, 
	 CONSTRAINT "RADIOLOGY_FK" FOREIGN KEY ("P_ID")
	  REFERENCES  "PATIENT" ("P_ID") ENABLE, 
	 CONSTRAINT "RADIOLOGY_FK3" FOREIGN KEY ("D_ID")
	  REFERENCES  "DOCTOR" ("D_ID") ENABLE
   )



CREATE TABLE  "RADIOLOGY_DEPT" 
   (	"RD_ID" VARCHAR2(8), 
	"RD_NAME" VARCHAR2(25), 
	"ADDRESS" VARCHAR2(25), 
	"BLOOD_GROUP" VARCHAR2(4), 
	"PH_NO" NUMBER, 
	"PASSWORD" VARCHAR2(8), 
	 PRIMARY KEY ("RD_ID") ENABLE
   )


CREATE TABLE  "RECEPTIONIST" 
   (	"R_ID" VARCHAR2(8), 
	"R_NAME" VARCHAR2(25), 
	"R_ADDRESS" VARCHAR2(25), 
	"SALARY" NUMBER, 
	"BLOOD_GROUP" VARCHAR2(3), 
	"PASSWORD" VARCHAR2(12), 
	"PH_NO" NUMBER(10,0), 
	 PRIMARY KEY ("R_ID") ENABLE
   )



CREATE TABLE  "WARDS" 
   (	"WARD_NO" NUMBER, 
	"WARD_TYPE" VARCHAR2(20), 
	"TOTAL_BEDS" NUMBER, 
	"OCCUPIED" NUMBER, 
	"REMAINING" NUMBER, 
	 CONSTRAINT "WARDS_PK" PRIMARY KEY ("WARD_NO") ENABLE
   )









